### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by nukaboy** [nguyenq/tess4j#118]
Hi, when i call `tesseract.getWords(image, TessPageIteratorLevel.RIL_TEXTLINE)` i get this exception:
`java.lang.NullPointerException: null
    at net.sourceforge.tess4j.Tesseract.getWords(Tesseract.java:708) [tess4j-4.2.2.jar:4.2.2]
    at de.kelm.lsreader.ImageReader.read(ImageReader.java:104) [classes/:?]
    at de.kelm.lsreader.ImageReader.readLines(ImageReader.java:120) [classes/:?]
    at de.kelm.lsreader.MainClass.main(MainClass.java:131) [classes/:?]`

I had this issue since switching from 4.0.2 to 4.2.2

**Comment by nguyenq** [comment]
We tried the pertinent test case with `RIL_TEXTLINE` but could not reproduce the issue.
