### ISSUE TITLE
[main] ERROR net.sourceforge.tess4j.Tesseract - null

### ISSUE THREAD

**Issue by chinnarii** [nguyenq/tess4j#128]
When im running the script getting below error message. Please help me..
[main] ERROR net.sourceforge.tess4j.Tesseract - null
java.lang.NullPointerException: null
	at net.sourceforge.tess4j.Tesseract.dispose(Tesseract.java:826)
	at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:239)
	at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:194)
	at tess4j.example.TesseractExample.main(TesseractExample.java:24)
java.lang.NullPointerException

**Comment by dattatembare** [comment]
@chinnarii you have to explain what you are trying to do in `TesseractExample.java`, if you post your code and image that will be helpful.
