### ISSUE TITLE
java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by chenqiang718** [nguyenq/tess4j#144]
I run Tess4J under the CentOS5.
This is my issue:
java.lang.UnsatisfiedLinkError: /tmp/jna-3506402/jna3028164768438593975.tmp: ELF file's phentsize not the expected size
	at com.sun.jna.Native.open(Native Method)
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:263)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:403)
	at com.sun.jna.Library$Handler.<init>(Library.java:147)
	at com.sun.jna.Native.loadLibrary(Native.java:502)
	at com.sun.jna.Native.loadLibrary(Native.java:481)
	at net.sourceforge.tess4j.util.LoadLibs.getTessAPIInstance(LoadLibs.java:75)
	at net.sourceforge.tess4j.TessAPI.<clinit>(TessAPI.java:42)
	at net.sourceforge.tess4j.Tesseract.init(Tesseract.java:367)
	at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:280)
	at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:263)
	at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:244)
	at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:228)
	at com.adtime.data.servlet.AnalysisImg.getNumFromImage(AnalysisImg.java:81)
	at com.adtime.data.servlet.AnalysisImg.doPost(AnalysisImg.java:32)
	at com.adtime.data.servlet.AnalysisImg.doGet(AnalysisImg.java:36)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:867)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:542)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1588)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1557)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:502)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)

what should I do?
Thank you!

**Comment by nguyenq** [comment]
Web searches reveal that it may have something with compiling the native libraries. How did you build and install Tesseract?

**Comment by ShafqatShafi** [comment]
@nguyenq I am getting the same error on the client's machine. But working fine on my machine.
My machine specs:
i5 6200u

My client machine specs:
1) t4550 core 2 duo
2) i5 M450 

According to your comment here:
![git-issue](https://user-images.githubusercontent.com/39758207/53289803-cfbc8d80-37c0-11e9-9eed-66b9a5d95280.PNG)

It looks like that underlying CPU need to support AVX, so that project can work fine.
So, this theory proves to be right because my machine CPU supports AVX and both my client's machines do not.

So is there any workaround to this problem so that I can run my code on the client's machine.

**Comment by nguyenq** [comment]
@ShafqatShafi Your problem, which is different from that of OP, has been fixed in tess4j-4.3.1 release.

**Comment by ShafqatShafi** [comment]
@nguyenq do you mean that the error mentioned in this issue has been fixed in tess4j-4.3.1 release

**Comment by nguyenq** [comment]
The DLL in 4.3.1 has been rebuilt with no AVX so that it could load on any CPU.

**Comment by ShafqatShafi** [comment]
@nguyenq Okay thanks a lot

**Comment by chenqiang718** [comment]
> Web searches reveal that it may have something with compiling the native libraries. How did you build and install Tesseract?

https://www.cnblogs.com/arachis/p/OCR.html
I followed it install Tesseract. I success to use Tesseract command after installed it.
Thanks for your answer.

**Comment by chenqiang718** [comment]
@nguyenq

**Comment by nguyenq** [comment]
That site seems to direct you to install a very old version of Tesseract. So either install the lastest release or find the Tess4J version compatible with it.

**Comment by chenqiang718** [comment]
> That site seems to direct you to install a very old version of Tesseract. So either install the lastest Tesseract release or find and use the Tess4J version that is compatible with it.

@nguyenq thanks your help!
The issue is resolved.The reason is just that the version is incompatible.
