### ISSUE TITLE
java.lang.UnsatisfiedLinkError in tess4j

### ISSUE THREAD

**Issue by svijayakumar1** [nguyenq/tess4j#159]
Hi ,

I am getting error when I try to run the tessesract code in windows server 2016, 64bit. In my local PC it is working fine. When I try to run the code in windows server 2016, I am getting below error. Please help me

java.lang.UnsatisfiedLinkError: The specified module could not be found.

	at com.sun.jna.Native.open(Native Method) ~[jna-4.5.2.jar:4.5.2 (b0)]
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:288) ~[jna-4.5.2.jar:4.5.2 (b0)]
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:427) ~[jna-4.5.2.jar:4.5.2 (b0)]
	at com.sun.jna.Library$Handler.<init>(Library.java:179) ~[jna-4.5.2.jar:4.5.2 (b0)]
	at com.sun.jna.Native.loadLibrary(Native.java:569) ~[jna-4.5.2.jar:4.5.2 (b0)]
	at com.sun.jna.Native.loadLibrary(Native.java:544) ~[jna-4.5.2.jar:4.5.2 (b0)]
	at net.sourceforge.tess4j.util.LoadLibs.getTessAPIInstance(LoadLibs.java:81) ~[tess4j-4.0.0.jar:4.0.0]
	at net.sourceforge.tess4j.TessAPI.<clinit>(TessAPI.java:42) ~[tess4j-4.0.0.jar:4.0.0]
	at net.sourceforge.tess4j.Tesseract.init(Tesseract.java:364) ~[tess4j-4.0.0.jar:4.0.0]
	at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:277) ~[tess4j-4.0.0.jar:4.0.0]
	at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:209) ~[tess4j-4.0.0.jar:4.0.0]
	at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:193) ~[tess4j-4.0.0.jar:4.0.0]
	at com.test.job.MyQuartzJob.execute(MyQuartzJob.java:79) ~[classes/:na]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202) ~[quartz-2.2.1.jar:na]

**Comment by nguyenq** [comment]
Can you try with the latest version of Tess4J?

**Comment by svijayakumar1** [comment]
Hi Quan,

 Thank you for your reply. Could you please send me the link for the latest
version of tess4j so that I'll will download that file and test that error.

Thanks
Srikanth

**Comment by nguyenq** [comment]
https://mvnrepository.com/artifact/net.sourceforge.tess4j/tess4j
https://github.com/nguyenq/tess4j/releases

**Comment by svijayakumar1** [comment]
@nguyenq  Thank you so much . Error got cleared and it worked after using latest tess4J. 
After using latest Tess4J, I am getting the below warning printing continuously.
Warning: Invalid resolution 0 dpi. Using 70 instead. Could you please help me how to remove that. 

Also, When I start scanning pdf containing images, all of a sudden the program terminates with some number like 2, 14 which will be in red color

Warning: Invalid resolution 0 dpi. Using 70 instead.
Warning: Invalid resolution 0 dpi. Using 70 instead.

14 

Please help me how to avoid this termination. My task is to daily scan lakhs of pdfs to by continuously running tessesract job.

**Comment by nguyenq** [comment]
Please check out Issue https://github.com/nguyenq/tess4j/issues/157. Or you can elect to set `debug_file` variable to `/dev/null` to hide all warning messages.

AFAIK, Java is unable to capture exceptions generated from native codes.

**Comment by nguyenq** [comment]
Can this ticket be closed?

**Comment by svijayakumar1** [comment]
Yeah sure Quan.

**Comment by nguyenq** [comment]
You can close it yourself.

Thanks.
