### ISSUE TITLE
Can't read english text from Image

### ISSUE THREAD

**Issue by jack5505** [nguyenq/tess4j#181]
ITesseract instance = new Tesseract();
        instance.setDatapath("E:/WORKING PROJECT/tesseract/");
        instance.setLanguage("eng");
        String imgText =  instance.doOCR(new File("f:/Documents/fafe.png"));
        System.out.println(imgText);

It gives following errors After executing those code

Exception in thread "main" java.lang.Error: Invalid memory access
	at com.sun.jna.Native.invokePointer(Native Method)
	at com.sun.jna.Function.invokePointer(Function.java:470)
	at com.sun.jna.Function.invoke(Function.java:404)
	at com.sun.jna.Function.invoke(Function.java:315)
	at com.sun.jna.Library$Handler.invoke(Library.java:212)
	at com.sun.proxy.$Proxy0.TessBaseAPIGetUTF8Text(Unknown Source)
	at net.sourceforge.tess4j.Tesseract.getOCRText(Tesseract.java:437)
	at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:292)
	at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:213)
	at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:197)
	at com.company.Task.main(Task.java:18)
Error opening data file E:/WORKING PROJECT/tesseract/tessdata/eng.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to the parent directory of your "tessdata" directory.
Failed loading language 'eng'
Tesseract couldn't load any languages!

**Comment by nguyenq** [comment]
It should be:

`instance.setDatapath("E:/WORKING PROJECT/tesseract/tessdata");`

And you have `eng.traineddata` file in `tessdata` directory?

**Comment by jack5505** [comment]
yes

**Comment by nguyenq** [comment]
Make sure you use compatible `traineddata` files -- `fast` or `best`.

https://github.com/tesseract-ocr/

**Comment by nguyenq** [comment]
Can the ticket be closed?

**Comment by jack5505** [comment]
yes
