### ISSUE TITLE
java.lang.UnsatisfiedLinkError in Windows Server 2019 Datacenter

### ISSUE THREAD

**Issue by n-feliciano** [nguyenq/tess4j#182]
Hi, 

I am getting the following error in Windows Server 2019 Datacenter:

java.lang.UnsatisfiedLinkError: The specified module could not be found.

	at com.sun.jna.Native.open(Native Method)
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:278)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:455)
	at com.sun.jna.Library$Handler.<init>(Library.java:192)
	at com.sun.jna.Native.loadLibrary(Native.java:646)
	at com.sun.jna.Native.loadLibrary(Native.java:630)
	at net.sourceforge.tess4j.util.LoadLibs.getTessAPIInstance(LoadLibs.java:85)
	at net.sourceforge.tess4j.TessAPI.<clinit>(TessAPI.java:42)
	at net.sourceforge.tess4j.Tesseract.init(Tesseract.java:427)

I tried using tess4j 4.5.1 and 4.4.1 and 4.3.1.
I see that the liblept and libtesseract are successfully downloaded to C:\Users\<user>\AppData\Local\Temp\tess4j\win32-x86-64.  But I still get the error.
Can you help me?

Thank you,
Nuno

**Comment by nguyenq** [comment]
Is VC++ 2019 runtime installed on the server?

**Comment by n-feliciano** [comment]
Now it is! Thank you so much!
