### ISSUE TITLE
UnsatisfiedLinkError on Windows 10

### ISSUE THREAD

**Issue by silma85** [nguyenq/tess4j#184]
I get the above exception while trying to use tess4j on Windows 10 with Eclipse.
The following is the JNA debug output: 

```
Trying C:\tesseract\libtesseract411.dll
Looking for lib- prefix
Trying liblibtesseract411.dll
Looking in classpath from sun.misc.Launcher$AppClassLoader@18b4aac2 for libtesseract411
Found library resource at jar:file:/C:/Users/alema/.m2/repository/net/sourceforge/tess4j/tess4j/4.5.1/tess4j-4.5.1.jar!/win32-x86-64/libtesseract411.dll
...
Caused by: java.lang.UnsatisfiedLinkError: Impossibile trovare il modulo specificato.

	at com.sun.jna.Native.open(Native Method) ~[jna-4.5.2.jar:4.5.2 (b0)]
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:288) ~[jna-4.5.2.jar:4.5.2 (b0)]
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:427) ~[jna-4.5.2.jar:4.5.2 (b0)]
	at com.sun.jna.Library$Handler.<init>(Library.java:179) ~[jna-4.5.2.jar:4.5.2 (b0)]
	at com.sun.jna.Native.loadLibrary(Native.java:569) ~[jna-4.5.2.jar:4.5.2 (b0)]
	at com.sun.jna.Native.loadLibrary(Native.java:544) ~[jna-4.5.2.jar:4.5.2 (b0)]
	at net.sourceforge.tess4j.util.LoadLibs.getTessAPIInstance(LoadLibs.java:85) ~[tess4j-4.5.1.jar:4.5.1]

```
This is the directory **C:\tesseract** where evidently the system can't find the libraries, even if they are right there:

![image](https://user-images.githubusercontent.com/8859924/82028015-59da6580-9695-11ea-8d4f-cedfce8e8659.png)

The DLL's I copied from tess4j-4.5.1.jar and lept4j-1.13.0.jar.
It seems to fall back on DLL's extracted from the jars (and I can indeed find them in temp files), but I get the error anyway.
Any idea on what could cause it?

Thanks.

**Comment by nguyenq** [comment]
Is VC++ 2019 runtime installed on your machine?

**Comment by nguyenq** [comment]
You're good now? Can the ticket be closed?
