### ISSUE TITLE
Different OCR results

### ISSUE THREAD

**Issue by niran-kumar-79** [nguyenq/tess4j#210]
Hi,

I have installed tesseract v5.0.0-alpha.20201127 (Windows) and Test4j-4.5.4.jar (using java).

I can see different results for the same image,  Some chars are recognised properly when tested through command line but fails to recognise in java.

Any inputs appreciated.

Regards

Niranjan

**Comment by nguyenq** [comment]
It's because tess4j-4.5.4 is for Tesseract 4.1.1.

https://github.com/nguyenq/tess4j/releases

You can try tess4j-5.0.0-SNAPSHOT.

**Comment by niran-kumar-79** [comment]
> It's because tess4j-4.5.4 is for Tesseract 4.1.1.
> 
> https://github.com/nguyenq/tess4j/releases
> 
> You can try tess4j-5.0.0-SNAPSHOT.


I updated the jar with "tess4j-5.0.0-SNAPSHOT.jar" but facing the below issue, can you advise on the dependencies.

Exception in thread "main" java.lang.UnsatisfiedLinkError: The specified module could not be found.

	at com.sun.jna.Native.open(Native Method)
	at com.sun.jna.Native.open(Native.java:1759)
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:260)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:398)
	at com.sun.jna.Library$Handler.<init>(Library.java:147)
	at com.sun.jna.Native.loadLibrary(Native.java:412)
	at com.sun.jna.Native.loadLibrary(Native.java:391)
	at net.sourceforge.tess4j.util.LoadLibs.getTessAPIInstance(LoadLibs.java:85)
	at net.sourceforge.tess4j.TessAPI.<clinit>(TessAPI.java:42)
	at net.sourceforge.tess4j.Tesseract.init(Tesseract.java:443)
	at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:239)
	at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:211)
	at com.nws.ocr.processOCRonImage.getOCRDatafromImage(processOCRonImage.java:100)
	at com.nws.ocr.processOCRonImage.main(processOCRonImage.java:50)

**Comment by niran-kumar-79** [comment]
Hi, 

I picked the dependencies referring to the link.

https://github.com/nguyenq/tess4j/blob/master/pom.xml

advise for changes.

Regards

Niranjan

**Comment by nguyenq** [comment]
You probably miss the VC++ 2019 dependency.

**Comment by niran-kumar-79** [comment]
Re-verified the dependencies, and now it's working.

Also, had installed VC++ earlier (referring to old posts).

**Comment by niran-kumar-79** [comment]
> You probably miss the VC++ 2019 dependency.

-Re-verified all dependencies, now it's working.

VC++ was installed earlier. 

Thank you for your hep.
