### ISSUE TITLE
Can't link libtesseract411.dll

### ISSUE THREAD

**Issue by 0113bernoyoun** [nguyenq/tess4j#214]
I tried to run tess4j-4.5.4 and I saw below error.

```
exception in thread main java.lang.unsatisfiedlinkerror the specified module could not be found
	at com.sun.jna.Native.open(Native Method)
	at com.sun.jna.Native.open(Native.java:1759)
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:260)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:398)
	at com.sun.jna.Library$Handler.<init>(Library.java:147)
	at com.sun.jna.Native.loadLibrary(Native.java:412)
	at com.sun.jna.Native.loadLibrary(Native.java:391)
	at net.sourceforge.tess4j.util.LoadLibs.getTessAPIInstance(LoadLibs.java:85)
	at net.sourceforge.tess4j.TessAPI.<clinit>(TessAPI.java:42)
	at net.sourceforge.tess4j.Tesseract.init(Tesseract.java:427)
	at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:223)
	at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:195)
```

I installed 2013, 2015, 2017, 2019 vc++ runtime, but it has same problem.

I tried debugging and it doesn't seem to find libtesseract411.dll. Is there any way to fix it?

**Comment by nguyenq** [comment]
On Windows, the native DLLs are copied to C:\Users\<username>\AppData\Local\Temp\tess4j and loaded from there. The location is defined by `java.io.tmpdir` system property.

**Comment by leesonlee** [comment]
Hello, I've the same issue. The tmpdir is not set automatically with the 4.5.4 version. With the 4.5.3 there is no problem, it is normal. Ty

**Comment by nguyenq** [comment]
@leesonlee There was no change in this area. You can review the commits in the Repository for verification.

**Comment by nguyenq** [comment]
@0113bernoyoun Do you still have this problem? Have you tried with older versions?
