### ISSUE TITLE
Tesseract 5 Support

### ISSUE THREAD

**Issue by mithunatri** [nguyenq/tess4j#220]
Hi,

Any plans on supporting Tess4J for Tesseract 5? I currently get the following error when trying to start my application against Tesseract 5 -- 

```
Caused by: java.lang.UnsatisfiedLinkError: Error looking up function 'TessBaseAPIRecognizeForChopTest': /usr/lib/x86_64-linux-gnu/libtesseract.so.5.0.0: undefined symbol: TessBaseAPIRecognizeForChopTest
	at com.sun.jna.Function.<init>(Function.java:252)
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:600)
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:576)
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:562)
	at com.sun.jna.Native.register(Native.java:1852)
	at com.sun.jna.Native.register(Native.java:1723)
	at com.sun.jna.Native.register(Native.java:1443)
	at net.sourceforge.tess4j.TessAPI1.<clinit>(TessAPI1.java:41)

**Comment by nguyenq** [comment]
Make sure you use the lept4j version compatible with your Leptonica version.

**Comment by mithunatri** [comment]
That did it. Thank you so much! 

Closing this issue.
