### ISSUE TITLE
 error: Error looking up function 'TessBaseAPIInit5': dlsym(0x7fe46b6d06a0, TessBaseAPIInit5): symbol not found

### ISSUE THREAD

**Issue by saqiaqq** [nguyenq/tess4j#236]
when I run the code: ITessAPI.TessBaseAPI handle = TessAPI1.TessBaseAPICreate(); get the error, how can fix it?
my tess4j version is 5.4.0

Exception in thread "main" java.lang.UnsatisfiedLinkError: Error looking up function 'TessBaseAPIInit5': dlsym(0x7fe46b6d06a0, TessBaseAPIInit5): symbol not found
	at com.sun.jna.Function.<init>(Function.java:252)
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:604)
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:580)
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:566)
	at com.sun.jna.Native.register(Native.java:1904)
	at com.sun.jna.Native.register(Native.java:1775)
	at com.sun.jna.Native.register(Native.java:1493)
	at net.sourceforge.tess4j.TessAPI1.<clinit>(TessAPI1.java:41)
	at imageocr.VipOcrBase.<init>(VipOcrBase.java:34)
	at imageocr.VipOcrBase.getInstance(VipOcrBase.java:30)
	at imageocr.VipOcrBase.main(VipOcrBase.java:142)

**Comment by nguyenq** [comment]
`TessBaseAPIInit5` is a new API method in Tesseract 5.2.0, so it's likely that you're running an older version of Tesseract. Try to use a Tess4J library version compatible with your Tesseract installation.
