### ISSUE TITLE
UnsatisfiedLinkError: Add exception message with cause hint

### ISSUE THREAD

**Issue by 4F2E4A2E** [nguyenq/tess4j#5]
User should get a hint, that Visual C++ Redistributable must be installed. Here a example running on Windows 7 with version 2.0.2-SNAPSHOT:
```
java.lang.UnsatisfiedLinkError: Das angegebene Modul wurde nicht gefunden.

        at com.sun.jna.Native.open(Native Method)
        at com.sun.jna.Native.open(Native.java:1759)
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:260)
        at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:398)
        at com.sun.jna.Library$Handler.<init>(Library.java:147)
        at com.sun.jna.Native.loadLibrary(Native.java:412)
        at com.sun.jna.Native.loadLibrary(Native.java:391)
        at net.sourceforge.tess4j.util.LoadLibs.getTessAPIInstance(LoadLibs.java:68)
        at net.sourceforge.tess4j.TessAPI.<clinit>(TessAPI.java:41)
        at net.sourceforge.tess4j.Tesseract.init(Tesseract.java:286)
        at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:222)
        at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:171)
        at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:155)
        at com.example.tess4j.TestTess4J.test(TestTess4J.java:44)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
```

**Comment by nguyenq** [comment]
Looks like a useful message. But how would we know specifically that Visual C++ Redistributable is missing?

**Comment by 4F2E4A2E** [comment]
It seams that, this is only possible via file system or windows registry entries, both unsatisfying but maybe the only way. Another possibility would be to create a small application in c# that does the check for us...

**Comment by nguyenq** [comment]
We want to keep the codebase compact. What if on other platforms, the users
do not have other dependencies installed, would we try to find out and
notify them of those missing libraries too? Listing the required s/w in the
documentation and the project website should be sufficient.

**Comment by 4F2E4A2E** [comment]
We could give a hint in the exception.

> Am 23.01.2015 um 03:19 schrieb Quan Nguyen <notifications@github.com>:
> 
> We want to keep the codebase compact. What if on other platforms, the users 
> do not have other dependencies installed, would we try to find out and 
> notify them of those missing libraries too? Listing the required s/w in the 
> documentation and the project website should be sufficient. 
>

**Comment by jrehwaldt** [comment]
You could link to a page within your wiki, which can be updated as needed for different OS and versions. Just an idea.

**Comment by 4F2E4A2E** [comment]
Thank you for the input, it is very welcomed :+1: 

We try to deliver this kind of information together within the release, please check out the release page: 
https://github.com/nguyenq/tess4j/releases/
https://github.com/nguyenq/tess4j/releases/tag/tess4j-3.0.0
