### ISSUE TITLE
Using Tess4J in a Tomee environment

### ISSUE THREAD

**Issue by nicky508** [nguyenq/tess4j#78]
I have a piece of software which I would like to involved Tess4J in. Started in a normal Java project (in Eclipse) and implemented Tess4J (v 3.4.2). It works.
The I copied the piece of code to the piece of software it should work with, which runs in a tomee environment. Then I get the:

`
Caused by: java.lang.UnsatisfiedLinkError: The specified module could not be found..
        at com.sun.jna.Native.open(Native Method)
        at com.sun.jna.Native.open(Native.java:1759)
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:260)
        at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:398)
        at com.sun.jna.Library$Handler.<init>(Library.java:147)
        at com.sun.jna.Native.loadLibrary(Native.java:412)
        at com.sun.jna.Native.loadLibrary(Native.java:391)
        at net.sourceforge.tess4j.util.LoadLibs.getTessAPIInstance(LoadLibs.java:81)
        at net.sourceforge.tess4j.TessAPI.<clinit>(TessAPI.java:42)
        at net.sourceforge.tess4j.Tesseract.init(Tesseract.java:379)
        at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:292)
        at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:224)
        at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:208)
        at resc.info.linkedhub_oi.utility.Ocr.recognizeText(Ocr.java:37)
        at resc.info.linkedhub_oi.models.Document.imageOCR(Document.java:135)
        at resc.info.linkedhub_oi.models.Document.retrieveDocumentFromCMS(Document.java:123)
        at resc.info.linkedhub_oi.service.LinkedhubService.processNewPostPost(LinkedhubService.java:85)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.openejb.server.cxf.rs.PojoInvoker.performInvocation(PojoInvoker.java:43)
        at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
        ... 34 more`

I also ran: System.setProperty("jna.debug_load", "true");

Result: 
`
Looking in classpath from TomEEWebappClassLoader
  context: ROOT
  delegate: false
----------> Parent Classloader:
java.net.URLClassLoader@7ab2bfe1
 for /com/sun/jna/win32-x86-64/jnidispatch.dll
Found library resource at jar:file:/C:/Users/Nicky/git/LinkedHub_OI-Server/target/apache-tomee/webapps/ROOT/WEB-INF/lib/jna-4.1.0.jar!/com/sun/jna/win32-x86-64/jnidispatch.dll
Looking for library 'libtesseract3051'
Adding paths from jna.library.path: null
Trying libtesseract3051.dll
Adding system paths: []
Trying libtesseract3051.dll
Looking for lib- prefix
Trying liblibtesseract3051.dll
Looking in classpath from TomEEWebappClassLoader
  context: ROOT
  delegate: false
----------> Parent Classloader:
java.net.URLClassLoader@7ab2bfe1
 for libtesseract3051
Found library resource at jar:file:/C:/Users/Nicky/git/LinkedHub_OI-Server/target/apache-tomee/webapps/ROOT/WEB-INF/lib/tess4j-3.4.2.jar!/win32-x86-64/libtesseract3051.dll`

I read some issues and some people are arguing about Visual C++ 2015 x64 Redistributable, however this is windows specific. So how would I be able to solve this issue and run the code in a tomee?

**Comment by nicky508** [comment]
I run Java(TM) SE Runtime Environment (build 1.8.0_141-b15) 32 bit

**Comment by nguyenq** [comment]
What OS? If Windows, you would need Visual C++ 2015 x86 Redistributable.

**Comment by nguyenq** [comment]
Please try the latest version. It includes a fix for `UnsatisfiedLinkError` issues on Windows server environment.
