### ISSUE TITLE
tess4j master build

### ISSUE THREAD

**Issue by ahmed-tea** [nguyenq/tess4j#86]
When I build the tess4j-master with
ant test
I get this error
Buildfile: build.xml does not exist!

**Comment by nguyenq** [comment]
The version on GitHub is Maven-based. Download and install Maven, then `mvn test`.

**Comment by ahmed-tea** [comment]
@nguyenq I did and it give me 91 error

**Comment by ahmed-tea** [comment]
@nguyenq 
Results :

Tests in error: 
  testTessBaseAPIAnalyseLayout(net.sourceforge.tess4j.TessAPI1Test): The specified module could not be found.
(..)
  testTessBaseAPIAnalyseLayout(net.sourceforge.tess4j.TessAPI1Test): Could not initialize class net.sourceforge.tess4j.TessAPI1
  testChoiceIterator(net.sourceforge.tess4j.TessAPI1Test): Could not initialize class net.sourceforge.tess4j.TessAPI1
  testChoiceIterator(net.sourceforge.tess4j.TessAPI1Test): Could not initialize class net.sourceforge.tess4j.TessAPI1
  testTessBaseAPIGetUTF8Text(net.sourceforge.tess4j.TessAPI1Test): Could not initialize class net.sourceforge.tess4j.TessAPI1
  testTessBaseAPIGetUTF8Text(net.sourceforge.tess4j.TessAPI1Test): Could not initialize class net.sourceforge.tess4j.TessAPI1
  testOSD(net.sourceforge.tess4j.TessAPI1Test): Could not initialize class net.sourceforge.tess4j.TessAPI1
  testOSD(net.sourceforge.tess4j.TessAPI1Test): Could not initialize class net.sourceforge.tess4j.TessAPI1
  testTessBaseAPIGetUTF8Text_Pix(net.sourceforge.tess4j.TessAPI1Test): Could not initialize class net.sourceforge.tess4j.TessAPI1
  testTessBaseAPIGetUTF8Text_Pix(net.sourceforge.tess4j.TessAPI1Test): Could not initialize class net.sourceforge.tess4j.TessAPI1
  testTessBaseAPIGetInitLanguagesAsString(net.sourceforge.tess4j.TessAPI1Test): Could not initialize class net.sourceforge.tess4j.TessAPI1
  testTessBaseAPIGetInitLanguagesAsString(net.sourceforge.tess4j.TessAPI1Test): Could not initialize class net.sourceforge.tess4j.TessAPI1
  testTessBaseAPIGetComponentImages(net.sourceforge.tess4j.TessAPI1Test): Could not initialize class net.sourceforge.tess4j.TessAPI1
  testTessBaseAPIGetComponentImages(net.sourceforge.tess4j.TessAPI1Test): Could not initialize class net.sourceforge.tess4j.TessAPI1
  testTessBaseAPIRect(net.sourceforge.tess4j.TessAPI1Test): Could not initialize class net.sourceforge.tess4j.TessAPI1
  testTessBaseAPIRect(net.sourceforge.tess4j.TessAPI1Test): Could not initialize class net.sourceforge.tess4j.TessAPI1
  testTessBaseAPIGetBoolVariable(net.sourceforge.tess4j.TessAPI1Test): Could not initialize class net.sourceforge.tess4j.TessAPI1
  testTessBaseAPIGetBoolVariable(net.sourceforge.tess4j.TessAPI1Test): Could not initialize class net.sourceforge.tess4j.TessAPI1
  testTessBaseAPIPrintVariablesToFile(net.sourceforge.tess4j.TessAPI1Test): Could not initialize class net.sourceforge.tess4j.TessAPI1
  testTessBaseAPIPrintVariablesToFile(net.sourceforge.tess4j.TessAPI1Test): Could not initialize class net.sourceforge.tess4j.TessAPI1
  testTessBaseAPISetVariable(net.sourceforge.tess4j.TessAPI1Test): Could not initialize class net.sourceforge.tess4j.TessAPI1
  testTessBaseAPISetVariable(net.sourceforge.tess4j.TessAPI1Test): Could not initialize class net.sourceforge.tess4j.TessAPI1
  testResultRenderer(net.sourceforge.tess4j.TessAPI1Test): Could not initialize class net.sourceforge.tess4j.TessAPI1
  testResultRenderer(net.sourceforge.tess4j.TessAPI1Test): Could not initialize class net.sourceforge.tess4j.TessAPI1
  testTessBaseAPIInit4(net.sourceforge.tess4j.TessAPI1Test): Could not initialize class net.sourceforge.tess4j.TessAPI1
  testTessBaseAPIInit4(net.sourceforge.tess4j.TessAPI1Test): Could not initialize class net.sourceforge.tess4j.TessAPI1
  testTessBaseAPIGetLoadedLanguagesAsVector(net.sourceforge.tess4j.TessAPI1Test): Could not initialize class net.sourceforge.tess4j.TessAPI1
  testTessBaseAPIGetLoadedLanguagesAsVector(net.sourceforge.tess4j.TessAPI1Test): Could not initialize class net.sourceforge.tess4j.TessAPI1
  testTessBaseAPIGetAvailableLanguagesAsVector(net.sourceforge.tess4j.TessAPI1Test): Could not initialize class net.sourceforge.tess4j.TessAPI1
  testTessBaseAPIGetAvailableLanguagesAsVector(net.sourceforge.tess4j.TessAPI1Test): Could not initialize class net.sourceforge.tess4j.TessAPI1
  testTessBaseAPIGetHOCRText(net.sourceforge.tess4j.TessAPI1Test): Could not initialize class net.sourceforge.tess4j.TessAPI1
  testTessBaseAPIGetHOCRText(net.sourceforge.tess4j.TessAPI1Test): Could not initialize class net.sourceforge.tess4j.TessAPI1
  testResultIterator(net.sourceforge.tess4j.TessAPI1Test): Could not initialize class net.sourceforge.tess4j.TessAPI1
  testResultIterator(net.sourceforge.tess4j.TessAPI1Test): Could not initialize class net.sourceforge.tess4j.TessAPI1
  testTessVersion(net.sourceforge.tess4j.TessAPI1Test): Could not initialize class net.sourceforge.tess4j.TessAPI1
  testTessVersion(net.sourceforge.tess4j.TessAPI1Test): Could not initialize class net.sourceforge.tess4j.TessAPI1
  testTessBaseAPIAnalyseLayout(net.sourceforge.tess4j.TessAPITest): The specified module could not be found.
(..)
  testTessBaseAPIAnalyseLayout(net.sourceforge.tess4j.TessAPITest)
  testChoiceIterator(net.sourceforge.tess4j.TessAPITest): Could not initialize class net.sourceforge.tess4j.TessAPI
  testChoiceIterator(net.sourceforge.tess4j.TessAPITest)
  testTessBaseAPIGetUTF8Text(net.sourceforge.tess4j.TessAPITest): Could not initialize class net.sourceforge.tess4j.TessAPI
  testTessBaseAPIGetUTF8Text(net.sourceforge.tess4j.TessAPITest)
  testOSD(net.sourceforge.tess4j.TessAPITest): Could not initialize class net.sourceforge.tess4j.TessAPI
  testOSD(net.sourceforge.tess4j.TessAPITest)
  testTessBaseAPIGetUTF8Text_Pix(net.sourceforge.tess4j.TessAPITest): Could not initialize class net.sourceforge.tess4j.TessAPI
  testTessBaseAPIGetUTF8Text_Pix(net.sourceforge.tess4j.TessAPITest)
  testTessBaseAPIGetInitLanguagesAsString(net.sourceforge.tess4j.TessAPITest): Could not initialize class net.sourceforge.tess4j.TessAPI
  testTessBaseAPIGetInitLanguagesAsString(net.sourceforge.tess4j.TessAPITest)
  testTessBaseAPIGetComponentImages(net.sourceforge.tess4j.TessAPITest): Could not initialize class net.sourceforge.tess4j.TessAPI
  testTessBaseAPIGetComponentImages(net.sourceforge.tess4j.TessAPITest)
  testTessBaseAPIRect(net.sourceforge.tess4j.TessAPITest): Could not initialize class net.sourceforge.tess4j.TessAPI
  testTessBaseAPIRect(net.sourceforge.tess4j.TessAPITest)
  testTessBaseAPIGetBoolVariable(net.sourceforge.tess4j.TessAPITest): Could not initialize class net.sourceforge.tess4j.TessAPI
  testTessBaseAPIGetBoolVariable(net.sourceforge.tess4j.TessAPITest)
  testTessBaseAPIPrintVariablesToFile(net.sourceforge.tess4j.TessAPITest): Could not initialize class net.sourceforge.tess4j.TessAPI
  testTessBaseAPIPrintVariablesToFile(net.sourceforge.tess4j.TessAPITest)
  testTessBaseAPISetVariable(net.sourceforge.tess4j.TessAPITest): Could not initialize class net.sourceforge.tess4j.TessAPI
  testTessBaseAPISetVariable(net.sourceforge.tess4j.TessAPITest)
  testResultRenderer(net.sourceforge.tess4j.TessAPITest): Could not initialize class net.sourceforge.tess4j.TessAPI
  testResultRenderer(net.sourceforge.tess4j.TessAPITest)
  testTessBaseAPIInit4(net.sourceforge.tess4j.TessAPITest): Could not initialize class net.sourceforge.tess4j.TessAPI
  testTessBaseAPIInit4(net.sourceforge.tess4j.TessAPITest)
  testTessBaseAPIGetLoadedLanguagesAsVector(net.sourceforge.tess4j.TessAPITest): Could not initialize class net.sourceforge.tess4j.TessAPI
  testTessBaseAPIGetLoadedLanguagesAsVector(net.sourceforge.tess4j.TessAPITest)
  testTessBaseAPIGetAvailableLanguagesAsVector(net.sourceforge.tess4j.TessAPITest): Could not initialize class net.sourceforge.tess4j.TessAPI
  testTessBaseAPIGetAvailableLanguagesAsVector(net.sourceforge.tess4j.TessAPITest)
  testTessBaseAPIGetHOCRText(net.sourceforge.tess4j.TessAPITest): Could not initialize class net.sourceforge.tess4j.TessAPI
  testTessBaseAPIGetHOCRText(net.sourceforge.tess4j.TessAPITest)
  testResultIterator(net.sourceforge.tess4j.TessAPITest): Could not initialize class net.sourceforge.tess4j.TessAPI
  testResultIterator(net.sourceforge.tess4j.TessAPITest)
  testTessVersion(net.sourceforge.tess4j.TessAPITest): Could not initialize class net.sourceforge.tess4j.TessAPI
  testTessVersion(net.sourceforge.tess4j.TessAPITest)
  testDoOCR_SkewedImage(net.sourceforge.tess4j.Tesseract1Test): net.sourceforge.tess4j.TessAPI1
  testGetWords(net.sourceforge.tess4j.Tesseract1Test): net.sourceforge.tess4j.TessAPI1
  testDoOCR_File_Rectangle(net.sourceforge.tess4j.Tesseract1Test): net.sourceforge.tess4j.TessAPI1
  testDoOCR_BufferedImage(net.sourceforge.tess4j.Tesseract1Test): net.sourceforge.tess4j.TessAPI1
  testCreateDocuments(net.sourceforge.tess4j.Tesseract1Test): net.sourceforge.tess4j.TessAPI1
  testDoOCR_List_Rectangle(net.sourceforge.tess4j.Tesseract1Test): net.sourceforge.tess4j.TessAPI1
  testDoOCR_UNLV_Zone_File(net.sourceforge.tess4j.Tesseract1Test): net.sourceforge.tess4j.TessAPI1
  testGetSegmentedRegions(net.sourceforge.tess4j.Tesseract1Test): net.sourceforge.tess4j.TessAPI1
  testDoOCR_File(net.sourceforge.tess4j.Tesseract1Test): net.sourceforge.tess4j.TessAPI1
  testDoOCR_SkewedImage(net.sourceforge.tess4j.TesseractTest): Could not initialize class net.sourceforge.tess4j.TessAPI
  testGetWords(net.sourceforge.tess4j.TesseractTest): Could not initialize class net.sourceforge.tess4j.TessAPI
  testDoOCR_File_Rectangle(net.sourceforge.tess4j.TesseractTest): Could not initialize class net.sourceforge.tess4j.TessAPI
  testDoOCR_BufferedImage(net.sourceforge.tess4j.TesseractTest): Could not initialize class net.sourceforge.tess4j.TessAPI
  testCreateDocuments(net.sourceforge.tess4j.TesseractTest): Could not initialize class net.sourceforge.tess4j.TessAPI
  testDoOCR_List_Rectangle(net.sourceforge.tess4j.TesseractTest): Could not initialize class net.sourceforge.tess4j.TessAPI
  testDoOCR_UNLV_Zone_File(net.sourceforge.tess4j.TesseractTest): Could not initialize class net.sourceforge.tess4j.TessAPI
  testGetSegmentedRegions(net.sourceforge.tess4j.TesseractTest): Could not initialize class net.sourceforge.tess4j.TessAPI
  testDoOCR_File(net.sourceforge.tess4j.TesseractTest): Could not initialize class net.sourceforge.tess4j.TessAPI
  testFolderExtraction(net.sourceforge.tess4j.TestFolderExtraction): Could not initialize class net.sourceforge.tess4j.TessAPI

Tests run: 100, Failures: 0, Errors: 91, Skipped: 4

**Comment by ahmed-tea** [comment]
I changed my temp folder (my user name have a space so i changed the temp file to avoid that)
I tryed to set the jna.library.path to the dll path in the temp
I tryed to set the jna.library.path to the dll path in the tess4j folder
I copied dll to system32
I have visual stdio 2015 installed
Tesseract4 work as a standalone application
Still I have 91 error when i tray to buld tess4j to generate the jar file

**Comment by ahmed-tea** [comment]
If anyone have the same problem, you can use the command
mvn install -Dmaven.test.skip=true
to skip the test and get the jar file tess4j-4.0.0-SNAPSHOT.jar
I don't know what the mean of SNAPSHOT jar

**Comment by ahmed-tea** [comment]
@nguyenq 
I'm using tess4j 4 on windows 7 64 bit
I already using tesseract 4.0.0 as stand-alone application for months
I have a complete visual studio 2015 installed

**Comment by nguyenq** [comment]
Looks like you've successfully built the JAR file. What is your question?

**Comment by ahmed-tea** [comment]
I added the the JAR file to my application's libraries
The JNA make a copy of libtesseract400.dll into %TMP%\jna-254314504\jna5752688245872599740.dll
both file in the same size
It give this error
java.lang.UnsatisfiedLinkError: The specified module could not be found.
	at com.sun.jna.Native.open(Native Method)
	at com.sun.jna.Native.open(Native.java:1759)
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:260)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:398)
	at com.sun.jna.Native.register(Native.java:1396)
	at com.sun.jna.Native.register(Native.java:1156)
	at net.sourceforge.tess4j.TessAPI1.<clinit>(TessAPI1.java:41)

**Comment by ahmed-tea** [comment]
@nguyenq 
UnsatisfiedLinkError because libtesseract400.dll need libleptxxxx.dll
I downloaded libtesseract400.dll & liblept1741.dll from [https://github.com/tdhintz/tesseract4win64](url)
I generated the tess4j JAR with the downloaded libtesseract400.dll and copied liblept1741.dll into %TMP%\jna-254314504\
It linked the libtesseract400.dll 
Still MVN test builed give error
libtesseract400.dll inside the tess4j-master need liblept1753.dll and when i copied it from lept4j-1.9.2.jar it didn't work
may be there is a problem in liblept1753.dll
now it give me an error  "Invalid memory access"
threw exception [javax.servlet.ServletException: java.lang.Error: Invalid memory access] with root cause
java.lang.Error: Invalid memory access
	at net.sourceforge.tess4j.TessAPI1.TessBaseAPIGetUTF8Text(Native Method)
	at net.sourceforge.tess4j.Tesseract1.getOCRText(Tesseract1.java:413)
	at net.sourceforge.tess4j.Tesseract1.doOCR(Tesseract1.java:269)
	at net.sourceforge.tess4j.Tesseract1.doOCR(Tesseract1.java:191)
	at net.sourceforge.tess4j.Tesseract1.doOCR(Tesseract1.java:175)
When i set the env. variable TESSDATA_PREFIX as suggested by many
TessBaseAPIInit1 doesn't initialize with error
threw exception [javax.servlet.ServletException: java.lang.Error: Invalid memory access] with root cause
java.lang.Error: Invalid memory access
	at net.sourceforge.tess4j.TessAPI1.TessBaseAPIInit1(Native Method)
	at net.sourceforge.tess4j.Tesseract1.init(Tesseract1.java:349)
	at net.sourceforge.tess4j.Tesseract1.doOCR(Tesseract1.java:258)
	at net.sourceforge.tess4j.Tesseract1.doOCR(Tesseract1.java:191)
	at net.sourceforge.tess4j.Tesseract1.doOCR(Tesseract1.java:175)

**Comment by nguyenq** [comment]
You're making progress! `Invalid memory access` exceptions are usually having to do with incorrect path to `tessdata` folder. `setDatapath` properly, then you'd be good to go.

**Comment by ahmed-tea** [comment]
@nguyenq 
When I set tessdata folder by setting the TESSDATA_PREFIX  or setDatapath , the OCR didn't initialize 
When I don't set the tessdata, the OCR get initialized (That mean there is no problem in tessdata)
 The  **Invalid memory access** happend in TessBaseAPIGetUTF8Text (TessAPI1.class)
When it create a pointer (Pointer.class) to point to TessBaseAPIGetUTF8Text  return

**Comment by nguyenq** [comment]
What's your `tessdata` path and what value you pass in `setDatapath` method?

**Comment by ahmed-tea** [comment]
@nguyenq 
I tried to set tessdata path using
TESSDATA_PREFIX (env variable in Eclipse)
instance.setDatapath(LoadLibs.extractTessResources("tessdata").getParent());
instance.setDatapath(databathString);
When i debug with Eclipse, it read the path and assign it but the OCR cann't initialize
When i did'n set the tessdata path it get initialize but TessBaseAPIGetUTF8Text because return pointer

mvn test Never Work
I think the problem that tesseract dll try to find liblept1753.dll and didn't find it
I tryed to put  liblept1753.dll in the same folder(tess4j\win32-x86-64) of  libtesseract400.dll (i copied it from lept4j)
I think there is a problem in this copy of liblept1753.dll

**Comment by ahmed-tea** [comment]
@nguyenq 
I tried to set tessdata path using
TESSDATA_PREFIX (env variable in Eclipse)
instance.setDatapath(LoadLibs.extractTessResources("tessdata").getParent());
instance.setDatapath(databathString);
When i debug with Eclipse, it read the path and assign it but the OCR cann't initialize
When i did'n set the tessdata path it get initialize but TessBaseAPIGetUTF8Text because return pointer

mvn test Never Work
I think the problem that tesseract dll try to find liblept1753.dll and didn't find it
I tryed to put  liblept1753.dll in the same folder(tess4j\win32-x86-64) of  libtesseract400.dll (i copied it from lept4j)
I think there is a problem in this copy of liblept1753.dll

**Comment by ahmed-tea** [comment]
Using libtesseract400.dll & liblept1741.dll from https://github.com/tdhintz/tesseract4win64
Copying the liblept1741.dll into the folder %TMP%\jna-254314504\ 
Setting the env. variable TESSDATA_PREFIX value with the tessdata path C:\......\Tesseract\tessdata or C:\......\Tesseract (I think it depend on the tesseract lib. build version)
Setting instance.setOcrEngineMode(0) for OEM_TESSERACT_ONLY TessOcr Engine Mode
It work
The problem it work only for OEM_TESSERACT_ONLY TessOcr Engine Mode
It is not working for LSTM

**mvn test** Never Work

**Comment by nguyenq** [comment]
You shouldn't have to do all of that. Maybe starting from a clean slate would help.

**Comment by ahmed-tea** [comment]
I did it many times and i get the same result
I tried those libs https://github.com/charlesw/tesseract/tree/feature/321-Tesseract-4/src/lib/TesseractOcr and they didn't work too

**Comment by ahmed-tea** [comment]
@nguyenq 
I build tesseract and Leptonica and used them
Now mvn test work but it give an error

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project tess4j: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test failed: The forked VM terminated without saying properly goodbye. VM crash or System.exit called ? -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project tess4j: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test failed: The forked VM terminated without saying properly goodbye. VM crash or System.exit called ?
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:606)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test failed: The forked VM terminated without saying properly goodbye. VM crash or System.exit called ?
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:148)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:606)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: java.lang.RuntimeException: The forked VM terminated without saying properly goodbye. VM crash or System.exit called ?
    at org.apache.maven.plugin.surefire.booterclient.output.ForkClient.close (ForkClient.java:257)
    at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork (ForkStarter.java:301)
    at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run (ForkStarter.java:116)
    at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider (AbstractSurefireMojo.java:740)
    at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAllProviders (AbstractSurefireMojo.java:682)
    at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked (AbstractSurefireMojo.java:648)
    at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute (AbstractSurefireMojo.java:586)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:606)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
[ERROR]

Libs:
[win32-x86-64.zip](https://github.com/nguyenq/tess4j/files/1942736/win32-x86-64.zip)

**Comment by nguyenq** [comment]
A fix has just been committed and published to address `UnsatisfiedLinkError` issues on Windows server (related to Tomcat). Please try it out. Make sure you start from a clean slate.

**Comment by ahmed-tea** [comment]
@nguyenq 
After replacing the Tesseract and Leptonica (dlls) with my build dlls and the data files with the current tessdata
Now mvn test work without error

**Comment by nguyenq** [comment]
Excellent! If you have new issues, please feel free to open a new ticket.

**Comment by nguyenq** [comment]
Can the ticket be closed?
